version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_simpletodo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: SIMPLETODO_DB
      MYSQL_USER: myuser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:

# docker exec -it mariadb_simpletodo mariadb -u myuser -p
